[project]
name = "compass"
version = "0.1.0"
description = "An ansible configuration for setting up an indexer relay"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ansible>=10.7.0",
]
